# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0b43f2be7294d16452b9f7a94beaa27cb24c2aa691d5da7314431382cea140086f4555170cad7a10d186bbbf8e278f3ae3899dc16ecd81dd39c5800a2b6dde8

test:
  secret_key_base: 94faf0e8554dcf3876922f23c2acdad359c67d4ae28a86918681eac64f32c450e77af28137b0e06278600dbde12b52e8fdf3e96db2b9c743d24d0a4b54d5e044

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
